[package]
name = "marker-network-site-generator"
version = "0.1.0"
authors = ["David Rusu <davidrusu.me@gmail.com>"]
edition = "2018"

[dependencies]
handlebars = "3.5.4"
tokio = { version = "1", features = ["full"] }
lines-are-rusty = { path = "../lines-are-rusty" }
remarkable-cloud-api = { path = "../remarkable-rs/remarkable-cloud-api" }
structopt = "0.3.21"
serde_json = "1.0"
serde = "1.0"
anyhow = "1.0"
zip = "0.5"
url = "2.2.1"